#!/bin/bash
rm -f nohup.out
#nohup sudo PYTHONPATH=/home/pi/mshine:/home/pi/mshine/webapp python $* 2>&1 &
sudo PYTHONPATH=/home/pi/mshine:/home/pi/mshine/webapp python $* 2>&1
echo "exitcode="$? 
sudo chown pi.pi *
