#theme: jekyll-theme-merlot
remote_theme: pages-themes/slate 
#lang: ru-RU
title: Дистибот
description: Перегонка без хлопот
#baseurl: "https://vscherbo.github.io/distibot"
relative_url: "/distibot"
show_excerpts: true
google_analytics: UA-110946042-1
disqus:
    shortname: distibot_disqus
